In [2]:
import numpy as np

In [3]:
numbers1 = np.random.randint(10,100,6)

In [4]:
numbers2 = np.random.randint(10,100,6)

In [5]:
print(numbers1)
print(numbers2)



[47 69 37 38 81 30]
[71 59 77 39 66 72]


In [6]:
result = numbers1 + numbers2
print(result)



[118 128 114  77 147 102]


In [8]:
print(numbers1 + 10)

[57 79 47 48 91 40]


In [9]:
print(numbers1 - numbers2)

[-24  10 -40  -1  15 -42]


In [10]:
print((numbers1 * numbers2))

[3337 4071 2849 1482 5346 2160]


In [12]:
print(np.sin(numbers1))

[ 0.12357312 -0.11478481 -0.64353813  0.29636858 -0.62988799 -0.98803162]


In [14]:
print(np.sqrt(numbers1))

[6.8556546  8.30662386 6.08276253 6.164414   9.         5.47722558]


In [15]:
print(np.log(numbers1))

[3.8501476  4.2341065  3.61091791 3.63758616 4.39444915 3.40119738]


In [19]:
mnumbers1 = numbers1.reshape(2,3)
mnumbers2 = numbers2.reshape(2,3)

In [20]:
print(mnumbers1)
print(mnumbers2)

[[47 69 37]
 [38 81 30]]
[[71 59 77]
 [39 66 72]]


In [22]:
result = np.vstack((mnumbers1,mnumbers2))

In [23]:
result

array([[47, 69, 37],
       [38, 81, 30],
       [71, 59, 77],
       [39, 66, 72]])

In [24]:
result2 = np.hstack((mnumbers1,mnumbers2))




In [25]:
result2

array([[47, 69, 37, 71, 59, 77],
       [38, 81, 30, 39, 66, 72]])

In [34]:
yuksek = numbers1 >= 50

In [35]:
mod = numbers1 % 2 == 0

In [36]:
print(numbers1[mod])

[38 30]


In [37]:
print(numbers1[yuksek])


[69 81]
