In [1]:
import numpy as np


In [2]:
py_list = [1,2,3,4,5,6,7,8,9]



In [11]:
np_array = np.array([1,2,3,4,5,6,7,8,9])
print(np_array)

[1 2 3 4 5 6 7 8 9]


In [4]:
py_multi = [[1,2,3],[4,5,6],[7,8,9]]



In [5]:
np_multi = np_array.reshape(3,3)

In [6]:
print(py_multi)
print(np_multi)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(np_array.ndim)

1


In [13]:
print(np_multi.ndim)

2


In [14]:
np_array.shape




(9,)

In [10]:
np_multi.shape




(3, 3)