In [1]:

import numpy as np



In [5]:
np.array([1,3,5,7,9])



array([1, 3, 5, 7, 9])

In [6]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
result = np.ones(10)

print(result)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
np.linspace(0,100,5)


array([  0.,  25.,  50.,  75., 100.])

In [5]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [6]:
np.random.randint(0,10)

6

In [7]:

np.random.randint(0,3,1)

array([2])

In [8]:
np.random.rand(5)



array([0.31259711, 0.46858453, 0.0740282 , 0.54179002, 0.04880764])

In [10]:
np.random.randn(5)

array([-1.03028322, -0.15808207, -0.23630487, -1.5904712 ,  0.47957073])

In [14]:
np_array2 = np.arange(50)

In [16]:
np_multi = np_array2.reshape(5,10)

In [19]:
print(np_multi.sum(axis=1))

[ 45 145 245 345 445]


In [20]:

print(np_multi.sum(axis=0))

[100 105 110 115 120 125 130 135 140 145]


In [22]:
rnd_numbers = np.random.randint(1,100,10)

In [23]:
rnd_numbers.max()



93

In [24]:
rnd_numbers.min()

14

In [25]:
rnd_numbers.mean()

53.0

In [27]:
rnd_numbers.argmax()

9

In [28]:
rnd_numbers.argmin()

2