In [1]:
import numpy as np

In [2]:
numbers = np.array([0,5,10,15,20,25,50,75])

In [3]:
numbers[5]

25

In [5]:
numbers[-1]

75

In [6]:
numbers[0:3]



array([ 0,  5, 10])

In [7]:
numbers[3:]

array([15, 20, 25, 50, 75])

In [8]:
numbers[::]



array([ 0,  5, 10, 15, 20, 25, 50, 75])

In [9]:
numbers[::-1]

array([75, 50, 25, 20, 15, 10,  5,  0])

In [12]:
numbers2 = np.array([[0,5,10],[15,20,25],[50,75,85]])



In [13]:
numbers2



array([[ 0,  5, 10],
       [15, 20, 25],
       [50, 75, 85]])

In [14]:
numbers2[0]

array([ 0,  5, 10])

In [15]:
numbers[0][0]

0

In [16]:
numbers2[1][2]

25

In [17]:
numbers2[1,2]

25

In [18]:
numbers2[:,2]

array([10, 25, 85])

In [19]:
numbers2[:,0:2]

array([[ 0,  5],
       [15, 20],
       [50, 75]])

In [21]:
numbers2[-1,:]

array([50, 75, 85])

In [22]:
numbers2[:2,:2]



array([[ 0,  5],
       [15, 20]])

In [23]:
arr1 = np.arange(0,10)
arr2 = arr1

In [25]:
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [26]:
arr2[0]=20

In [27]:
print(arr1)
print(arr2)

[20  1  2  3  4  5  6  7  8  9]
[20  1  2  3  4  5  6  7  8  9]


In [28]:
arr1 = np.arange(0,10)
arr2 = arr1.copy()
arr2[0]=20
print(arr1)
print(arr2)


[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]
